apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: gym-dev
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: gym_catalog
  DATABASE_URL: postgresql://postgres:postgres@gym-catalog-postgres:15432/gym_catalog
